//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoomWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int Id { get; set; }
        public int IdRoom { get; set; }
        public int IdChatUser { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int IdState { get; set; }
    
        public virtual ChatUser ChatUser { get; set; }
        public virtual cState cState { get; set; }
        public virtual Room Room { get; set; }
    }
}
